import type { ColumnDefinition } from "./columns";
import type { EnumDefinition } from "./types";

interface SchemaTable {
  __tableName: string;
  __columns: Record<string, ColumnDefinition>;
  [key: string]: unknown;
}

interface ConvertOptions {
  includeDrop?: boolean;
}

/**
 * Converts a schema object to PostgreSQL SQL statements
 * Similar to Drizzle's db push command
 */
export function schemaToPostgres(
  schema: Record<string, SchemaTable>,
  options: ConvertOptions = {}
): string {
  const { includeDrop = false } = options;
  const sqlStatements: string[] = [];

  // Collect all enums first
  const enums = new Map<string, EnumDefinition>();
  for (const table of Object.values(schema)) {
    for (const column of Object.values(table.__columns)) {
      if (column.__enumName && (column as any).__enumDef) {
        const enumDef = (column as any).__enumDef as EnumDefinition;
        enums.set(enumDef.name, enumDef);
      }
    }
  }

  // Create enums
  if (enums.size > 0) {
    sqlStatements.push("-- Create enums");
    for (const enumDef of enums.values()) {
      if (includeDrop) {
        sqlStatements.push(`DROP TYPE IF EXISTS ${enumDef.name} CASCADE;`);
      }
      const values = enumDef.values.map((v) => `'${v}'`).join(", ");
      sqlStatements.push(`CREATE TYPE ${enumDef.name} AS ENUM (${values});`);
    }
    sqlStatements.push("");
  }

  // Create tables
  for (const table of Object.values(schema)) {
    const tableName = table.__tableName;
    const columns = table.__columns;

    sqlStatements.push(`-- Create ${tableName} table`);

    if (includeDrop) {
      sqlStatements.push(`DROP TABLE IF EXISTS public.${tableName} CASCADE;`);
    }

    sqlStatements.push(`CREATE TABLE IF NOT EXISTS public.${tableName} (`);

    const columnDefs: string[] = [];
    const foreignKeys: string[] = [];
    const indexes: { name: string; column: string; unique: boolean }[] = [];

    // Process columns
    for (const [columnName, column] of Object.entries(columns)) {
      const parts: string[] = [`  ${columnName}`];

      // Add column type
      parts.push(columnTypeToPostgres(column));

      // Add constraints
      if (column.primaryKey) {
        parts.push("PRIMARY KEY");
      }
      if (column.notNull && !column.primaryKey) {
        parts.push("NOT NULL");
      }
      if (column.unique) {
        parts.push("UNIQUE");
      }

      // Add default value
      if (column.__isIdentity) {
        parts.push("GENERATED BY DEFAULT AS IDENTITY");
      } else if (column.defaultValue !== undefined) {
        parts.push(
          `DEFAULT ${formatDefaultValue(column.defaultValue, column.type)}`
        );
      } else if (column.type === "uuid" && column.primaryKey) {
        parts.push("DEFAULT gen_random_uuid()");
      } else if (column.type === "timestamp" || column.type === "timestamptz") {
        if (columnName === "created_at" || columnName === "updated_at") {
          parts.push("DEFAULT now()");
        }
      }

      columnDefs.push(parts.join(" "));

      // Collect foreign keys
      if (column.__references) {
        foreignKeys.push(
          `  CONSTRAINT fk_${tableName}_${columnName} FOREIGN KEY (${columnName}) REFERENCES public.${column.__references.table}(${column.__references.column}) ON DELETE CASCADE`
        );
      }

      // Collect indexes
      if (column.__index) {
        indexes.push({
          name: `${tableName}_${columnName}_idx`,
          column: columnName,
          unique: false,
        });
      }
      if (column.__uniqueIndex) {
        indexes.push({
          name: `${tableName}_${columnName}_unique_idx`,
          column: columnName,
          unique: true,
        });
      }
    }

    // Combine column definitions and foreign keys
    const allDefs = [...columnDefs, ...foreignKeys];
    sqlStatements.push(allDefs.join(",\n"));
    sqlStatements.push(");");
    sqlStatements.push("");

    // Create indexes
    if (indexes.length > 0) {
      sqlStatements.push(`-- Create indexes for ${tableName}`);
      for (const index of indexes) {
        const uniqueKeyword = index.unique ? "UNIQUE " : "";
        sqlStatements.push(
          `CREATE ${uniqueKeyword}INDEX IF NOT EXISTS ${index.name} ON public.${tableName}(${index.column});`
        );
      }
      sqlStatements.push("");
    }
  }

  return sqlStatements.join("\n");
}

function columnTypeToPostgres(column: ColumnDefinition): string {
  const { type } = column;
  let pgType = "";

  switch (type) {
    case "text":
      pgType = "TEXT";
      break;
    case "varchar":
      if (column.__enumName) {
        pgType = column.__enumName;
      } else {
        pgType = column.length ? `VARCHAR(${column.length})` : "VARCHAR";
      }
      break;
    case "char":
      pgType = column.length ? `CHAR(${column.length})` : "CHAR";
      break;
    case "integer":
      pgType = "INTEGER";
      break;
    case "smallint":
      pgType = "SMALLINT";
      break;
    case "bigint":
      pgType = "BIGINT";
      break;
    case "serial":
      pgType = "INTEGER";
      break;
    case "bigserial":
      pgType = "BIGINT";
      break;
    case "real":
      pgType = "REAL";
      break;
    case "doublePrecision":
      pgType = "DOUBLE PRECISION";
      break;
    case "numeric":
      if (column.precision && column.scale !== undefined) {
        pgType = `NUMERIC(${column.precision}, ${column.scale})`;
      } else if (column.precision) {
        pgType = `NUMERIC(${column.precision})`;
      } else {
        pgType = "NUMERIC";
      }
      break;
    case "decimal":
      if (column.precision && column.scale !== undefined) {
        pgType = `DECIMAL(${column.precision}, ${column.scale})`;
      } else if (column.precision) {
        pgType = `DECIMAL(${column.precision})`;
      } else {
        pgType = "DECIMAL";
      }
      break;
    case "boolean":
      pgType = "BOOLEAN";
      break;
    case "timestamp":
      pgType = "TIMESTAMP";
      break;
    case "timestamptz":
      pgType = "TIMESTAMPTZ";
      break;
    case "date":
      pgType = "DATE";
      break;
    case "time":
      pgType = "TIME";
      break;
    case "uuid":
      pgType = "UUID";
      break;
    case "json":
      pgType = "JSON";
      break;
    case "jsonb":
      pgType = "JSONB";
      break;
    default:
      pgType = "TEXT";
  }

  if (column.__isArray) {
    pgType += "[]";
  }

  return pgType;
}

function formatDefaultValue(value: unknown, type: string): string {
  if (value === null) return "NULL";
  if (typeof value === "string") {
    if (type === "uuid" && value === "gen_random_uuid()") {
      return value;
    }
    return `'${value}'`;
  }
  if (typeof value === "number" || typeof value === "bigint") {
    return value.toString();
  }
  if (typeof value === "boolean") {
    return value ? "TRUE" : "FALSE";
  }
  return `'${JSON.stringify(value)}'`;
}
