import type { ColumnChange, LocalSchema, SchemaDiff } from "./diff";
import type { DbSchema } from "./introspect";
import { mapColumnType } from "./introspect";

export interface ColumnRenames {
  [tableName: string]: Map<string, string>;
}

export function generateSql(
  diff: SchemaDiff,
  localSchema: LocalSchema,
  schema: Record<string, any>,
  renames: ColumnRenames,
  dbSchema?: DbSchema
): string[] {
  const statements: string[] = [];

  // 1. Create new enums first (tables may depend on them)
  for (const enumChange of diff.enumChanges) {
    if (enumChange.type === "create" && enumChange.values) {
      const values = enumChange.values.map((v) => `'${v}'`).join(", ");
      statements.push(`CREATE TYPE ${enumChange.name} AS ENUM (${values});`);
    }
  }

  // 1.5. Create/Update functions (tables/triggers may depend on them)
  if (diff.functionChanges) {
    for (const funcChange of diff.functionChanges) {
      if (funcChange.type === "create" && funcChange.def) {
        statements.push(generateCreateFunctionSql(funcChange.def));
      } else if (funcChange.type === "drop") {
        // We need the signature to drop safely if overloaded, but for now assuming name unique or drop all
        // Postgres requires argument types to drop specific function unless we use DROP FUNCTION name
        // Use DROP FUNCTION IF EXISTS name(args) if possible, or just name if not overloaded.
        // If we have def, we know args.
        if (funcChange.def) {
          const argTypes = funcChange.def.args.map((a) => a.type).join(", ");
          statements.push(
            `DROP FUNCTION IF EXISTS ${funcChange.name}(${argTypes});`
          );
        } else {
          // Fallback if we don't have def (shouldn't happen with current diff logic)
          statements.push(`DROP FUNCTION IF EXISTS ${funcChange.name};`);
        }
      }
    }
  }

  // 2. Add new enum values
  for (const enumChange of diff.enumChanges) {
    if (enumChange.type === "add_value" && enumChange.added_values) {
      for (const value of enumChange.added_values) {
        statements.push(`ALTER TYPE ${enumChange.name} ADD VALUE '${value}';`);
      }
    }
  }

  // 3. Create new tables
  for (const tableName of diff.tablesToCreate) {
    const table = Object.values(schema).find(
      (t: any) => t.__tableName === tableName
    );
    if (!table) continue;

    const columnDefs: string[] = [];
    const constraints: string[] = [];

    for (const [columnName, column] of Object.entries(
      table.__columns as Record<string, any>
    )) {
      const parts: string[] = [columnName];

      // Type
      let typeStr = "";
      if (column.__enumName) {
        typeStr = column.__enumName;
      } else {
        typeStr = mapColumnType(column.type).toUpperCase();
      }

      if (column.__isArray) {
        typeStr += "[]";
      }
      parts.push(typeStr);

      // Constraints
      if (column.primaryKey) parts.push("PRIMARY KEY");
      if (column.notNull && !column.primaryKey) parts.push("NOT NULL");
      if (column.unique) parts.push("UNIQUE");

      // Default
      if (column.__isIdentity) {
        parts.push("GENERATED BY DEFAULT AS IDENTITY");
      } else if (column.type === "uuid" && column.primaryKey) {
        parts.push("DEFAULT gen_random_uuid()");
      } else if (column.defaultValue !== undefined) {
        parts.push(
          `DEFAULT ${formatDefault(column.defaultValue, column.type)}`
        );
      }

      columnDefs.push(`  ${parts.join(" ")}`);

      // Foreign key constraints
      if (column.__references) {
        constraints.push(
          `  CONSTRAINT fk_${tableName}_${columnName} FOREIGN KEY (${columnName}) ` +
            `REFERENCES public.${column.__references.table}(${column.__references.column}) ON DELETE CASCADE`
        );
      }
    }

    const allDefs = [...columnDefs, ...constraints];
    statements.push(
      `CREATE TABLE public.${tableName} (\n${allDefs.join(",\n")}\n);`
    );

    // Enable RLS if requested
    if (table.__rlsEnabled) {
      statements.push(
        `ALTER TABLE public.${tableName} ENABLE ROW LEVEL SECURITY;`
      );
    }

    // Create indexes for new table
    for (const [columnName, column] of Object.entries(
      table.__columns as Record<string, any>
    )) {
      if (column.__index) {
        statements.push(
          `CREATE INDEX ${tableName}_${columnName}_idx ON public.${tableName}(${columnName});`
        );
      }
      if (column.__uniqueIndex) {
        statements.push(
          `CREATE UNIQUE INDEX ${tableName}_${columnName}_unique_idx ON public.${tableName}(${columnName});`
        );
      }
    }

    // Create composite indexes for new table
    if (table.__indexes) {
      for (const idx of table.__indexes) {
        const unique = idx.unique ? "UNIQUE " : "";
        const columns = idx.columns.join(", ");
        const idxName =
          idx.name ||
          `${tableName}_${idx.columns.join("_")}_${idx.unique ? "unique_" : ""}idx`;
        statements.push(
          `CREATE ${unique}INDEX ${idxName} ON public.${tableName}(${columns});`
        );
      }
    }

    // Create policies for new table
    if (table.__policies) {
      for (const policy of table.__policies) {
        statements.push(generateCreatePolicySql(tableName, policy));
      }
    }

    // Create triggers for new table
    if (table.__triggers) {
      for (const trigger of table.__triggers) {
        statements.push(generateCreateTriggerSql(tableName, trigger));
      }
    }
  }

  // 4. Handle table modifications
  for (const [tableName, tableDiff] of diff.tableChanges) {
    const tableRenames = renames[tableName] || new Map<string, string>();
    const renamedFrom = new Set(tableRenames.keys());
    const renamedTo = new Set(tableRenames.values());

    // Column renames
    for (const [oldName, newName] of tableRenames) {
      statements.push(
        `ALTER TABLE public.${tableName} RENAME COLUMN ${oldName} TO ${newName};`
      );
    }

    // Drop foreign keys first (they may reference columns being modified)
    for (const fk of tableDiff.foreignKeysToDrop) {
      if (fk.constraint_name) {
        statements.push(
          `ALTER TABLE public.${tableName} DROP CONSTRAINT ${fk.constraint_name};`
        );
      }
    }

    // Drop indexes that are being removed
    for (const idx of tableDiff.indexesToDrop) {
      // Check if this index depends on columns being dropped (and not renamed)
      // If so, the index will be dropped automatically by the column drop, so we skip explicit drop
      const isImplicitlyDropped = idx.columns.some((col) => {
        return tableDiff.columnsToDrop.includes(col) && !renamedFrom.has(col);
      });

      if (isImplicitlyDropped) {
        continue;
      }

      statements.push(`DROP INDEX IF EXISTS ${idx.index_name};`);
    }

    // Column modifications (type, nullable, unique changes)
    for (const mod of tableDiff.columnsToModify) {
      const stmts = generateColumnModification(
        tableName,
        mod,
        schema,
        dbSchema
      );
      statements.push(...stmts);
    }

    // Add new columns (excluding renamed ones)
    for (const columnName of tableDiff.columnsToAdd) {
      if (renamedTo.has(columnName)) continue;

      const table = Object.values(schema).find(
        (t: any) => t.__tableName === tableName
      );
      if (!table) continue;

      const column = (table.__columns as Record<string, any>)[columnName];
      if (!column) continue;

      const parts: string[] = [];

      // Type
      let typeStr = "";
      if (column.__enumName) {
        typeStr = column.__enumName;
      } else {
        typeStr = mapColumnType(column.type).toUpperCase();
      }

      if (column.__isArray) {
        typeStr += "[]";
      }
      parts.push(typeStr);

      // For adding NOT NULL columns, we need a default or to add nullable first
      if (column.notNull && column.defaultValue === undefined) {
        // Add as nullable first, then set not null
        statements.push(
          `ALTER TABLE public.${tableName} ADD COLUMN ${columnName} ${parts.join(" ")};`
        );
        statements.push(
          `ALTER TABLE public.${tableName} ALTER COLUMN ${columnName} SET NOT NULL;`
        );
      } else {
        if (column.notNull) parts.push("NOT NULL");
        if (column.unique) parts.push("UNIQUE");
        if (column.__isIdentity) {
          parts.push("GENERATED BY DEFAULT AS IDENTITY");
        } else if (column.defaultValue !== undefined) {
          parts.push(
            `DEFAULT ${formatDefault(column.defaultValue, column.type)}`
          );
        }
        statements.push(
          `ALTER TABLE public.${tableName} ADD COLUMN ${columnName} ${parts.join(" ")};`
        );
      }

      // Add index if specified
      if (column.__index) {
        statements.push(
          `CREATE INDEX ${tableName}_${columnName}_idx ON public.${tableName}(${columnName});`
        );
      }
      if (column.__uniqueIndex) {
        statements.push(
          `CREATE UNIQUE INDEX ${tableName}_${columnName}_unique_idx ON public.${tableName}(${columnName});`
        );
      }

      // Add foreign key if specified
      if (column.__references) {
        statements.push(
          `ALTER TABLE public.${tableName} ADD CONSTRAINT fk_${tableName}_${columnName} ` +
            `FOREIGN KEY (${columnName}) REFERENCES public.${column.__references.table}(${column.__references.column}) ON DELETE CASCADE;`
        );
      }
    }

    // Drop columns (excluding renamed ones)
    for (const columnName of tableDiff.columnsToDrop) {
      if (renamedFrom.has(columnName)) continue;
      statements.push(
        `ALTER TABLE public.${tableName} DROP COLUMN ${columnName};`
      );
    }

    // Add new foreign keys
    for (const fk of tableDiff.foreignKeysToAdd) {
      statements.push(
        `ALTER TABLE public.${tableName} ADD CONSTRAINT fk_${tableName}_${fk.column} ` +
          `FOREIGN KEY (${fk.column}) REFERENCES public.${fk.foreign_table}(${fk.foreign_column}) ON DELETE ${fk.on_delete || "CASCADE"};`
      );
    }

    // Add new indexes
    for (const idx of tableDiff.indexesToAdd) {
      const unique = idx.is_unique ? "UNIQUE " : "";
      const columns = idx.columns.join(", ");
      statements.push(
        `CREATE ${unique}INDEX ${idx.index_name} ON public.${tableName}(${columns});`
      );
    }

    // RLS Changes
    if (tableDiff.rlsChange) {
      if (tableDiff.rlsChange.to) {
        statements.push(
          `ALTER TABLE public.${tableName} ENABLE ROW LEVEL SECURITY;`
        );
      } else {
        statements.push(
          `ALTER TABLE public.${tableName} DISABLE ROW LEVEL SECURITY;`
        );
      }
    }

    // Drop policies
    for (const policy of tableDiff.policiesToDrop || []) {
      statements.push(
        `DROP POLICY IF EXISTS "${policy.name}" ON public.${tableName};`
      );
    }

    // Drop triggers
    for (const trigger of tableDiff.triggersToDrop || []) {
      statements.push(
        `DROP TRIGGER IF EXISTS "${trigger.name}" ON public.${tableName};`
      );
    }

    // Create policies
    for (const policy of tableDiff.policiesToCreate || []) {
      if (policy.def) {
        statements.push(generateCreatePolicySql(tableName, policy.def));
      }
    }

    // Create triggers
    for (const trigger of tableDiff.triggersToCreate || []) {
      if (trigger.def) {
        statements.push(generateCreateTriggerSql(tableName, trigger.def));
      }
    }
  }

  // 5. Drop tables
  for (const tableName of diff.tablesToDrop) {
    statements.push(`DROP TABLE public.${tableName} CASCADE;`);
  }

  // 6. Drop unused enums (after tables that might use them are dropped)
  for (const enumChange of diff.enumChanges) {
    if (enumChange.type === "drop") {
      statements.push(`DROP TYPE ${enumChange.name};`);
    }
  }

  // Note: Removing enum values is not directly supported in PostgreSQL
  // We log a warning but don't generate SQL for it
  for (const enumChange of diff.enumChanges) {
    if (enumChange.type === "remove_value" && enumChange.removed_values) {
      console.warn(
        `Warning: Cannot remove values from enum "${enumChange.name}". ` +
          `Values to remove: ${enumChange.removed_values.join(", ")}. ` +
          `This requires recreating the enum type.`
      );
    }
  }

  return statements;
}

function generateCreatePolicySql(tableName: string, policy: any): string {
  const parts = [`CREATE POLICY "${policy.name}" ON public.${tableName}`];

  const cmd = (policy.cmd || policy.on || "ALL").toUpperCase();
  if (cmd !== "ALL") {
    parts.push(`FOR ${cmd}`);
  }

  const roles = policy.roles || policy.to || ["public"];
  if (roles.length > 0) {
    parts.push(`TO ${roles.join(", ")}`);
  }

  const qual = policy.qual || policy.using;
  if (qual) {
    parts.push(`USING (${qual})`);
  }

  const withCheck = policy.with_check || policy.withCheck;
  if (withCheck) {
    parts.push(`WITH CHECK (${withCheck})`);
  }

  return parts.join(" ") + ";";
}

function generateCreateFunctionSql(def: any): string {
  // CREATE OR REPLACE FUNCTION name(args) RETURNS return_type LANGUAGE language AS $$ definition $$;
  const args = def.args
    .map((a: any) => `${a.name || ""} ${a.type}`)
    .join(", ")
    .trim();
  const definition = def.definition.trim();
  // Ensure definition is wrapped in $$, or simple quotes if not.
  // Assuming definition is the body.
  // If definition starts with BEGIN, it might need $$ wrappers.
  // Ideally, introspection returns the body without outer wrappers if it parsed it well,
  // but pg_get_function_def returns full CREATE statement.
  // But we are using pg_proc.prosrc which is the body.

  // Check if we need to wrap body in $$.
  // Simple heuristic: always wrap in $$.
  return `CREATE OR REPLACE FUNCTION ${def.name}(${args}) RETURNS ${def.return_type} LANGUAGE ${def.language} AS $$
${definition}
$$;`;
}

function generateCreateTriggerSql(tableName: string, trigger: any): string {
  // CREATE TRIGGER name BEFORE/AFTER/INSTEAD OF event ON tableName FOR EACH ROW/STATEMENT EXECUTE FUNCTION func();
  const events = trigger.events.join(" OR ");
  const timing = trigger.event || trigger.timing; // trigger.event in schema, timing in diff
  const orientation = trigger.forEach || trigger.orientation || "ROW";
  const funcName = trigger.function || trigger.function_name || trigger.call;

  // Resolve function name if it is an object
  const resolvedFuncName =
    typeof funcName === "string" ? funcName : funcName.name;

  return `CREATE TRIGGER "${trigger.name}" ${timing} ${events} ON public.${tableName} FOR EACH ${orientation} EXECUTE FUNCTION ${resolvedFuncName}();`;
}

function generateColumnModification(
  tableName: string,
  mod: ColumnChange,
  schema: Record<string, any>,
  dbSchema?: DbSchema
): string[] {
  const statements: string[] = [];
  const { column, changes } = mod;

  // Type change
  if (changes.type) {
    const table = Object.values(schema).find(
      (t: any) => t.__tableName === tableName
    );
    const colDef = table?.__columns?.[column];

    let newType = "";
    if (colDef?.__enumName) {
      newType = colDef.__enumName;
    } else {
      newType = mapColumnType(colDef?.type || changes.type.to).toUpperCase();
    }

    if (colDef?.__isArray) {
      newType += "[]";
    }

    // Check if the column has a default value in the database
    const dbColumn = dbSchema?.tables.get(tableName)?.columns.get(column);
    const hasDbDefault = dbColumn?.column_default != null;

    if (hasDbDefault) {
      // Drop default first, then change type, then re-add default if needed
      statements.push(
        `ALTER TABLE public.${tableName} ALTER COLUMN ${column} DROP DEFAULT;`
      );
    }

    statements.push(
      `ALTER TABLE public.${tableName} ALTER COLUMN ${column} TYPE ${newType} USING ${column}::${newType};`
    );

    // Re-add default if the local schema specifies one
    if (colDef?.defaultValue !== undefined) {
      const defaultVal = formatDefault(
        colDef.defaultValue,
        colDef.__enumName || colDef.type
      );
      statements.push(
        `ALTER TABLE public.${tableName} ALTER COLUMN ${column} SET DEFAULT ${defaultVal};`
      );
    }
  }

  // Nullable change
  if (changes.nullable) {
    if (changes.nullable.to) {
      // Making nullable
      statements.push(
        `ALTER TABLE public.${tableName} ALTER COLUMN ${column} DROP NOT NULL;`
      );
    } else {
      // Making not null
      statements.push(
        `ALTER TABLE public.${tableName} ALTER COLUMN ${column} SET NOT NULL;`
      );
    }
  }

  // Unique change
  if (changes.unique) {
    if (changes.unique.to) {
      // Adding unique constraint
      statements.push(
        `ALTER TABLE public.${tableName} ADD CONSTRAINT ${tableName}_${column}_unique UNIQUE (${column});`
      );
    } else {
      // Dropping unique constraint
      statements.push(
        `ALTER TABLE public.${tableName} DROP CONSTRAINT IF EXISTS ${tableName}_${column}_unique;`
      );
    }
  }

  // Identity change
  if (changes.identity) {
    if (changes.identity.to) {
      // Adding identity
      // Must drop default if exists before adding identity
      statements.push(
        `ALTER TABLE public.${tableName} ALTER COLUMN ${column} DROP DEFAULT;`
      );
      statements.push(
        `ALTER TABLE public.${tableName} ALTER COLUMN ${column} ADD GENERATED BY DEFAULT AS IDENTITY;`
      );
    } else {
      // Dropping identity
      statements.push(
        `ALTER TABLE public.${tableName} ALTER COLUMN ${column} DROP IDENTITY IF EXISTS;`
      );
      // Re-add default if one exists in definition
      const table = Object.values(schema).find(
        (t: any) => t.__tableName === tableName
      );
      const colDef = table?.__columns?.[column];
      if (colDef?.defaultValue !== undefined) {
        const defaultVal = formatDefault(
          colDef.defaultValue,
          colDef.__enumName || colDef.type
        );
        statements.push(
          `ALTER TABLE public.${tableName} ALTER COLUMN ${column} SET DEFAULT ${defaultVal};`
        );
      }
    }
  }

  return statements;
}

function formatDefault(value: unknown, type: string): string {
  if (value === null) return "NULL";
  if (typeof value === "string") {
    if (type === "uuid" && value === "gen_random_uuid()") {
      return value;
    }
    return `'${value}'`;
  }
  if (typeof value === "number" || typeof value === "bigint")
    return value.toString();
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  return `'${JSON.stringify(value)}'`;
}
